- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-2021111508360949600000000a.cdqpbjkethv0.us-east-1.rds.amazonaws.com" 
    login_user: "david"
    login_password: "devopspblproject"
    name: wordpress
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.lineinfile:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^localhost', line: "terraform-2021111508360949600000000a.cdqpbjkethv0.us-east-1.rds.amazonaws.com" }
    - { regexp: '^username_here', line: "wordpress" }
    - { regexp: '^database_name_here', line: "wordpress" }
    - { regexp: '^password_here', line: "w0rdpr33$" }