- name: Download wordpress compressed file
  ansible.builtin.get_url:
    url: http://wordpress.org/latest.tar.gz
    dest: /home/ec2-user/latest.tar.gz
    

- name: unzip the compressed file
  ansible.builtin.unarchive:
    src: latest.tar.gz
    dest: /home/ec2-user/
    remote_src: yes

- name: Copy config.php
  ansible.builtin.copy:
    src: /home/ec2-user/wordpress/wp-config-sample.php
    dest: /home/ec2-user/wordpress/wp-config.php
    force: yes
    remote_src: yes

- name: deploy the code
  ansible.builtin.copy:
    src: /home/ec2-user/wordpress/.
    dest: /var/www/html/
    force: yes
    remote_src: yes

- name: create healthstatus file
  ansible.builtin.file:
    path: /var/www/html/healthstatus
    state: touch


- name: Allow apache to modify /var/www/html
  community.general.sefcontext:
    target: /var/www/html/
    ignore_selinux_state: yes
    setype: httpd_sys_content_t
  notify: Restart httpd

