---
- name: mounting share
  command: sudo mount -t efs -o tls,accesspoint=fsap-06a770f110ead9e3f fs-01d51a09393ef8846:/ /var/www

- name: install httpd on the webserver
  ansible.builtin.yum:
    enablerepo: "BaseOS,AppStream"
    name: "httpd"
    state: present

- name: install PHP
  ansible.builtin.yum:
    name:
      - php 
      - php-mysqlnd
      - php-gd 
      - php-curl
      - php-common
      - php-fpm
      - php-mbstring
      - php-opcache 
      - php-xml
      - php-intl 
      - php-json
    state: present

- name: ensure php-fpm is started and enabled
  ansible.builtin.service:
     name: php-fpm
     state: reloaded
     enabled: yes
  notify: Restart php-fpm

- import_tasks: setup-db.yml

- import_tasks: setup-site.yml

- name: ensure httpd is started and enabled
  ansible.builtin.service:
     name: httpd 
     state: started 
     enabled: yes































