- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-2021111211063265400000000c.crrh6ajas8hr.us-east-1.rds.amazonaws.com"
    login_user: "david"
    login_password: "devopspblproject"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input tooling credentials
  ansible.builtin.lineinfile:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', line: "terraform-2021111211063265400000000c.crrh6ajas8hr.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', line: "tooling" }
    - { regexp: '^tooling', line: "toolingdb" }
    - { regexp: '^admin', line: "t00l!n#" }


