---
- hosts: tag_Name_dACS_nginx
- name: nginx assignment
  import_playbook: ../static-assignments/nginx.yml

- hosts: tag_Name_ACS_tooling 
- name: tooling assignment
  import_playbook: ../static-assignments/tooling.yml

- hosts: tag_Name_ACS_wordpress
- name: wordpress assignment
  import_playbook: ../static-assignments/wordpress.yml

- hosts: tag_Name_ACS_jenkins
- name: jenkins assignment
  import_playbook: ../static-assignments/jenkins.yml  

- hosts: tag_Name_ACS_sonarqube
- name: sonarqube assignment
  import_playbook: ../static-assignments/sonar.yml

- hosts: tag_Name_ACS_artifactory
- name: artifactory assignment
  import_playbook: ../static-assignments/jfrog.yml



